### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by amaotone** [amaotone/hostcomp#7]
- [ ] upload test data #3
- [ ] set scoring function #5 
- [x] set password for leaderboard #6
- [ ] delete submission
